name 'blag'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures blag'
long_description 'Installs/Configures blag'
version '0.1.0'

depends 'mysql', '~> 6.1.2'
depends 'nginx', '~> 2.7.6'
depends 'hhvm', '~> 0.6.0'
depends 'wordpress', '~> 3.0.0'
