---
driver:
  name: vagrant
  customize:
    memory: 1024
    cpus: 2
  network:
    - ["forwarded_port", {guest: 80, host: 8080}]

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    data_bags_path: './test/integration/default/data_bags'
    encrypted_data_bag_secret_key_path: './test/integration/default/encrypted_data_bag_secret'
    run_list:
      - recipe[ops-linux::default]
      - recipe[blag::default]
    attributes:
