---
driver:
  name: vagrant
  customize:
    memory: 1024
    cpus: 2
  network:
    - ["forwarded_port", {guest: 80, host: 8080}]

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[blag::default]
    attributes:
