name 'blag'
maintainer 'Matt Kleinsasser'
maintainer_email 'mxkx@hotmail.com'
license ''
description 'Installs/Configures blag'
long_description 'Installs/Configures blag'
version '1.0.0'

depends 'wordpress', '~> 3.0.0'
depends 'ops-linux', '~> 1.0.0'
depends 'ops-mysql', '~> 1.0.0'
depends 'ops-nginx', '~> 1.0.0'
