name 'ops-nginx'
maintainer 'Matt Kleinsasser'
maintainer_email 'mxkx@hotmail.com'
license ''
description 'Wrapper cookbook for nginx'
long_description 'Wrapper cookbook for nginx'
version '0.1.0'

depends 'nginx', '~> 2.7.6'
depends 'hhvm', '~> 0.6.0'
